run:
    - GTX1080Ti
    - GTX1080Ti-PTXPLUS


GTX1080Ti:
    base_file: "$GPGPUSIM_ROOT/configs/GeForceGTX1080Ti/gpgpusim.config"
    extra_params: ""

GTX1080Ti-PTXPLUS:
    base_file: "$GPGPUSIM_ROOT/configs/GeForceGTX1080Ti/gpgpusim.config"
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1"
