global:
    knobs_shorts: 
        gpgpu_max_insn_issue_per_warp: "mxiipw"
        gpgpu_num_sched_per_core: "nspc"
        gpgpu_shader_core_pipeline: "scp"
        gpgpu_shader_registers: "sr"
        gpgpu_shader_cta: "sc"
        gpgpu_num_reg_banks: "nrb"
        gpgpu_shmem_num_banks: "snb" 
        gpgpu_shmem_size: "ss"
        gpgpu_n_clusters: "nc"
        gpgpu_n_cores_per_cluster: "ncpc"
        gpgpu_operand_collector_num_units_sp: "ocnusp"
        gpgpu_operand_collector_num_units_sfu: "ocnusfu"
        gpgpu_operand_collector_num_units_mem: "ocnum"
        gpgpu_operand_collector_num_in_ports_sp: "ocnipsp"
        gpgpu_operand_collector_num_in_ports_sfu: "ocnipsfu"
        gpgpu_operand_collector_num_in_ports_mem: "ocnipm"
        gpgpu_operand_collector_num_out_ports_sp: "ocnopsp"
        gpgpu_operand_collector_num_out_ports_sfu: "ocnopsfu"
        gpgpu_operand_collector_num_out_ports_mem: "ocnopm"
        gpgpu_num_sp_units: "nspu"
        gpgpu_num_sfu_units: "nsfu"
        gpgpu_num_mem_units: "nmu"
        gpgpu_cache:dl1: "cdl1"
        gpgpu_cache:dl2: "cdl2"
    
    knobs: 
        mxiipw: "max_insn_issue_per_warp"
        nspc: "sched_per_core"
        scp: "shader_core_pipeline"
        sr: "shader_registers"
        sc: "shader_cta"
        nrb: "num_reg_banks"
        snb: "shmem_banks" 
        ss: "shmem_size"
        nc: "clusters"
        ncpc: "cores_per_cluster"
        ocnusp: "operand_collector_units_sp"
        ocnusfu: "operand_collector_units_sfu"
        ocnum: "operand_collector_units_mem"
        ocnipsp: "operand_collector_in_ports_sp"
        ocnipsfu: "operand_collector_num_in_ports_sfu"
        ocnipm: "operand_collector_in_ports_mem"
        ocnopsp: "operand_collector_out_ports_sp"
        ocnopsfu: "operand_collector_out_ports_sfu"
        ocnopm: "operand_collector_out_ports_mem"
        nspu: "sp_units"
        nsfu: "sfu_units"
        nmu: "mem_units"
        cdl1: "l1D_size" 
        cdl2: "l2D_size" 

    stat_shorts:
        kernel_launch_uid: "kernel_id"
        kernel_name: "kernel"
        "gpgpu_simulation_time(sec)": "time(sec)" 
        gpu_tot_sim_insn: "tot_insn"
        gpu_sim_insn: "insn"
        gpu_sim_cycle: "cycles"
        gpu_tot_sim_cycle: "tot_cycles"
        gpu_tot_ipc: "tot_ipc"
        L2_total_cache_misses: "tot_L2_misses"
        L1D_total_cache_misses: "tot_L1D_misses"
        L1D_total_cache_accesses: "tot_L1D_accesses"
        L2_total_cache_accesses: "tot_L2_accesses"
        L1D_total_cache_miss_rate: "tot_L1D_miss_rate"
        L2_total_cache_miss_rate: "tot_L2_miss_rate"
        L1I_total_cache_accesses: "tot_L1I_accesses"
        L1I_total_cache_misses: "tot_L1I_misses"
        L1I_total_cache_miss_rate: "tot_L1I_miss_rate"
        averagemflatency: "mem_fetch_latency"
        Stall: "warp_stall_cycles"
        W0_Idle: "warp_idle_cycles"
        W0_Scoreboard: "warp_scoreboard_idle"
        W_Occupancy: "warp_occupancy"
        Utilization: "warp_utilization"
        "L2_BW(GBps)": "L2_BW(GBps)"
        "L2_BW_total(GBps)": "tot_L2_BW(GBps)"
        gpgpu_n_load_insn: "load_insn"
        bw_util: "bw_util"
        gpgpu_n_store_insn: "store_insn"
        gpgpu_n_mem_read_local: "local_mem_reads"
        gpgpu_n_mem_read_global: "global_mem_reads"
        gpgpu_n_mem_write_local: "local_mem_writes"
        gpgpu_n_mem_write_global: "global_mem_writes"
        gpgpu_n_stall_shd_mem_stall: "memory_stalls"
        gpgpu_n_tot_thrd_icount: "tot_thread_insn"
        gpgpu_n_tot_w_icount: "tot_w_insn"

    bench_shorts:
        backprop-rodinia-2.0-ft: bp-rod
        bfs-rodinia-2.0-ft: bfs-rod
        hotspot-rodinia-2.0-ft: hs-rod
        heartwall-rodinia-2.0-ft: hw-rod
        kmeans-rodinia-2.0-ft: km-rod
        lud-rodinia-2.0-ft: lud-rod
        nw-rodinia-2.0-ft: nw-rod
        nn-rodinia-2.0-ft: nn-rod
        pathfinder-rodinia-2.0-ft: pf-rod
        srad_v2-rodinia-2.0-ft: sr2-rod
        streamcluster-rodinia-2.0-ft: sc-rod
        BlackScholes-sdk-4.1.15: bs-sdk
        MonteCarlo-sdk-4.1.15: mc-sdk
        SobolQRNG-sdk-4.1.15: sq-sdk
        binomialOptions-sdk-4.1.15: bo-sdk
        convolutionSeparable-sdk-4.1.15: cs-sdk
        fastWalshTransform-sdk-4.1.15: fwt-sdk
        histogram-sdk-4.1.15: hst-sdk
        mergeSort-sdk-4.1.15: ms-sdk
        quasirandomGenerator-sdk-4.1.15: qg-sdk
        reduction-sdk-4.1.15: red-sdk
        scalarProd-sdk-4.1.15: sp-sdk
        scan-sdk-4.1.15: sca-sdk
        sortingNetworks-sdk-4.1.15: sn-sdk
        transpose-sdk-4.1.15: tra-sdk
        vectorAdd-sdk-4.1.15: vec-sdk
        nbody-sdk-4.1.15: nbo-sdk
        Mandelbrot-sdk-4.1.15: mb-sdk
        AES-ispass2009-1.0: aes-isp
        BFS-ispass2009-1.0: bfs-isp
        LIB-ispass2009-1.0: lib-isp 
        LPS-ispass2009-1.0: lps-isp
        MUM-ispass2009-1.0: mum-isp
        NN-ispass2009-1.0: nn-isp
        RAY-ispass2009-1.0: ray-isp
        NQU-ispass2009-1.0: nqu-isp
        STO-ispass2009-1.0: sto-isp
        spmv-parboil-0.2: spm-par
        stencil-parboil-0.2: ste-par
        tpacf-parboil-0.2: tpac-par
        sad-parboil-0.2: sad-par
        histo-parboil-0.2: hst-par
        sgemm-parboil-0.2: sge-par
        mri-q-parboil-0.2: mri-par
        cutcp-parboil-0.2: cut-par
        average: avg


subplots_one_line_per_bench.py:
    stats_to_plot:
        - gpu_tot_sim_cycle
        - gpu_tot_ipc
        - L1D_total_cache_miss_rate
        - L2_total_cache_miss_rate
        - Utilization
        # - "gpgpu_simulation_time(sec)"
        # - W_Occupancy
        # - L1I_total_cache_miss_rate
        # - averagemflatency
        # - "L2_BW(GBpersec)"
        # - "L2_BW_total(GBpersec)"
        # - gpgpu_n_store_insn
        # - gpgpu_n_mem_read_local
        # - gpgpu_n_mem_read_global
        # - gpgpu_n_mem_write_local
        # - gpgpu_n_mem_write_global
        # - gpgpu_n_stall_shd_mem_stall
    parboil:
        grid:
            columns: 3
            rows: 3
    sdk:
        grid:
            columns: 5
            rows: 4
    rodinia:
        grid:
            columns: 4
            rows: 3
    ispass:
        grid:
            columns: 4
            rows: 3
    figsize: 
        w: 8
        h: 6
    nticks:
        x: 3
        y: 3
    ticks:
        x:
            fontsize: '8'
        y: 
            fontsize: '8'
    marker: '+'
    legend:
        loc: 'best'
        handlelength: 0
        fancybox: True
        framealpha: 0.5
        fontsize: 9.5
        labelspacing: 0
        borderpad: 0.5
        handletextpad: 0.5
        borderaxespad: 0

    knobs_to_plot: 
        - mxiipw
        - nspc
        - scp
        - sr
        - sc
        - nrb
        - snb 
        - ss
        - nspu
        - nsfu
        - nmu
        - "mxiipw,nspu,nsfu,nmu,pw"
        - "mxiipw,nspu,nsfu,nmu,pw,scp"
        - "ocnusp,ocnusfu,ocnum,ocnipsp,ocnipsfu,ocnipm,ocnopsp,ocnopsfu,ocnopm,nrb"
        # - cdl1 
        # - cdl2 
        # - nc
        # - ncpc
        # - ocnusp
        # - ocnusfu
        # - ocnum
        # - ocnipsp
        # - ocnipsfu
        # - ocnipm
        # - ocnopsp
        # - ocnopsfu
        # - ocnopm
